### ISSUE TITLE
Kindly make some improvement 

### ISSUE THREAD

**Issue by impmp** [jeevan-lal/Excel-Data-Filler-V4#1]
1. Make a video on how to "Upload File" function will work.
2. It is not working on pop up fields

**Comment by jeevan-lal** [comment]
@impmp 

Videos related to this extension will come on this channel only.

https://www.youtube.com/@ctechhindi

For more information you can message us on WhatsApp group.

https://chat.whatsapp.com/F2AdHoZRvr8HiAbvWqKlVS

Send Which Popup Fields.
