### ISSUE TITLE
after entery of data previos fields are empty

### ISSUE THREAD

**Issue by schand77** [jeevan-lal/Excel-Data-Filler-V4#12]
Uploading WhatsApp Video 2024-09-15 at 16.51.34.mp4…

**Comment by jeevan-lal** [comment]
Share proper details.

**Comment by schand77** [comment]
I have tried to add data through your excellent data filler extension, while on running this data entry is visible after proceeding to next field previous field data is missing, how to over come such problem, even I have sumbmitted video also you can observe.
Thank you

**Comment by jeevan-lal** [comment]
Try Field Option - Trigger Javascript Event - (input, blur)

https://efiller-doc.netlify.app/documentation/form-fields/field-settings.html#trigger-javascript-event

If not working then send me a video

**Comment by schand77** [comment]
Sir I have tried as you said but same issue, I think web designed like
that, so it will not work me, thank you
