### ISSUE TITLE
Contact Developer hello

### ISSUE THREAD

**Issue by anil77789** [jeevan-lal/Excel-Data-Filler-V4#19]
### Discussed in https://github.com/jeevan-lal/Excel-Data-Filler-V4/discussions/17

<div type='discussions-op-text'>

<sup>Originally posted by **DerAlex101** October 18, 2024</sup>
Hello developer,
I wrote you via your website and email but not sure if my messages arrived.
what is a way to get in contact with you ? </div>

**Comment by anil77789** [comment]
can you guide me how to use this extension

**Comment by anil77789** [comment]
yes

**Comment by jeevan-lal** [comment]
Watch videos and documentation if any problem coming then contact to whatsapp group.

https://efiller-doc.netlify.app/documentation/#join
