### ISSUE TITLE
page reload problem

### ISSUE THREAD

**Issue by penumarru** [jeevan-lal/Excel-Data-Filler-V4#22]
select value from drop down list , page reloads every time , web form have 10 fields , slect first field value, page refresh automatically, then starts from first, after that select second field value pages refresh , then starts form first , agin seect value of first filed, and second field, then select third field value , again pages reloads . web page have drop downlists sir, after selecting each field page refreshes, 
so what is the solution of the above issue sir, please resolve

**Comment by jeevan-lal** [comment]
What you said is not a problem, some sites have similar forms and when the page is refreshed, the filler starts again and does not re-select the fields that have already been selected.

**Comment by penumarru** [comment]
No Sir, first select value from drop down list, then page refresh and then display second filed, after selecting drop down value from second field, page refresh and agin starts from first one  and so on ....after selecting value from 9th field , page refresh and aging starts field 1 , field 2, field 3.....and so on...
its a continuous loop like

**Comment by jeevan-lal** [comment]
Join whatsapp group and send me video - https://efiller-doc.netlify.app/documentation/#join
