### ISSUE TITLE
site not found

### ISSUE THREAD

**Issue by Irigepallirbk** [jeevan-lal/Excel-Data-Filler-V4#23]
i want to use excellent data filler extension in chrome browser but after added to chrome it is showing that site is not found, kindly help me to resolve this issue

**Comment by jeevan-lal** [comment]
It's on track, wait it will take some time

**Comment by Irigepallirbk** [comment]
How much time it takes time please

**Comment by Irigepallirbk** [comment]
![Screenshot (1)](https://github.com/user-attachments/assets/7bdcf035-15f6-4b04-915c-569539af8969)

**Comment by Irigepallirbk** [comment]
I request you to please pursue this issue, unfortunately i commented **closed**. kindly update on this issue please

**Comment by jeevan-lal** [comment]
I have purchased the domain https://stable.edfiller.in so that there is no problem in future. The new version (4.8.0) of the extension which is linked to this new site will be published today or tomorrow and then you can use it.

**Comment by jeevan-lal** [comment]
Working now
