### ISSUE TITLE
Generate Excell Template NOT SHOWING

### ISSUE THREAD

**Issue by rbsknalgonda** [jeevan-lal/Excel-Data-Filler-V4#5]
Not showing the option generate excell template. please update the options
![Screenshot from 2024-02-06 09-37-04](https://github.com/jeevan-lal/Excel-Data-Filler-V4/assets/159101067/4a3d8455-0ab2-4cd9-bfc4-dadeb01e0324)

**Comment by jeevan-lal** [comment]
This is extension new version. In this version first insert site then download excel template in extension page.

1. Insert Site
2. Download Excel Template from Extension Page

![](https://efiller-doc.netlify.app/image/download-excel-template-01.png)

Docs

https://efiller-doc.netlify.app/documentation/structure.html

Video

https://www.youtube.com/watch?v=PZn1Rm83TS0

**Comment by rbsknalgonda** [comment]
Thank you so Much Sir 🙏🙏🙏
I Request you to show one detailed video in YouTube about RBSK Children
Screening data entry with some examples. It will be very helpful for us.

**Comment by jeevan-lal** [comment]
Join group 

https://efiller-doc.netlify.app/documentation/#join
