### ISSUE TITLE
Warning: Unable to receive data from Excel

### ISSUE THREAD

**Issue by DGKA9** [jeevan-lal/Excel-Data-Filler-V4#6]
I uploaded an Excel (.xlsx) file to Upload Excel, but the form is not receiving the data. It seems that only the first value in Excel is being processed. Subsequent values are not being handled.

**Comment by jeevan-lal** [comment]
Sorry for Delay

Please set form success response in extension site settings, if success response matched then extension move to next excel entry.

https://efiller-doc.netlify.app/documentation/form-response/form-success-response.html
